module.exports = {
    AUTO_VIEW_STATUS: 'true',
    AUTO_LIKE_STATUS: 'true',
    AUTO_RECORDING: 'true',
    AUTO_LIKE_EMOJI: ['❤️', '😮', '💫', '🍂', '🌟','🫀', '👀', '🤖', '👾', '🥰', '🗿', '💜', '💙', '🌝', '🖤', '💚'],
    PREFIX: '.',
    MAX_RETRIES: 3,
    GROUP_INVITE_LINK: 'https://chat.whatsapp.com/IsRYqiHgd5UAtjCF59FZ4y?mode=gi_t',
    ADMIN_LIST_PATH: './admin.json',
    IMAGE_PATH: 'https://files.catbox.moe/btwcnl.jpg',
    NEWSLETTER_JID: '120363416743041101@newsletter',
    NEWSLETTER_MESSAGE_ID: '428',
    OTP_EXPIRY: 300000,
    NEWS_JSON_URL: '',
    BOT_NAME: 'ᥫ𝐃𝐑᭡𝐄𝐑𝐅𝐀𝐍★⃝🔥👻 ',
    OWNER_NAME: 'ᥫ𝐃𝐑᭡𝐄𝐑𝐅𝐀𝐍★⃝🔥👻 ',
    OWNER_NUMBER: '+923306137477',
    BOT_VERSION: '1.0.0',
    BOT_FOOTER: '> ᥫ𝐃𝐑᭡𝐄𝐑𝐅𝐀𝐍★⃝🔥👻 ',
    CHANNEL_LINK: 'https://whatsapp.com/channel/p',
};
